### ISSUE TITLE
Quiz cannot continue with no participant answers

### ISSUE THREAD

**Issue by timloudon** [calumtomeny/quiz-master#198]
**Describe the bug**
if no contestants answer then the Quiz Host cannot continue to the next question.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to quiz.coffee
2. Create a quiz with questions
3. All participants fail to answer a question
4. See that the quiz host cannot continue the quiz if no contestants have answered because the calculate scores button does not appear

**Expected behaviour**
The quiz host should be able to continue the quiz even if no contestants answer a question.

**Actual behaviour**
The "calculate scores" button does not appear and the host cannot continue the quiz.

**Comment by richielewis** [comment]
Fixed in PR 197
